name: myworkflow

on:
  # push:
  #   branches:
  #     - main
  release:
    types:
      - published

jobs:
  myjob:
    name: My job
    permissions:
      id-token: write
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: build
        run: |
          python -m pip install --upgrade build
          python -m build

      # # TODO: publish should be separate job to minimize "permissions: id-token: write" scope
      - name: publish
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  # publish-job:
  #   name: publish job
  #   needs: myjob
  #   permissions:
  #     id-token: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: publish
  #       if: github.event_name == 'release'
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         repository-url: https://test.pypi.org/legacy/